# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint0
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
    - joint_finger_left
    - joint_finger_right
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    allowed_execution_duration_scaling: 1.2
    allowed_goal_duration_margin: 0.5
    joints:
      - joint0
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6

arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint0
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0
  gains:
    joint0: {p: 50000.0, i: 1000.0, d: 1000.0}
    joint1: {p: 3000.0, i: 1.0, d: 0.5}
    joint2: {p: 4000.0, i: 600.0, d: 10.0}
    joint3: {p: 1000.0, i: 2.0, d: 1.0}
    joint4: {p: 100.0, i: 1.0, d: 1.0}
    joint5: {p: 100.0, i: 1.0, d: 1.0}
    joint6: {p: 100.0, i: 1.0, d: 0.001}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
